$(document).ready(function(){
	$("#new").addClass("se");
	$(".use_header_ul1").hide();
	$("#all1").css("color","#000");
	$("#all2").css("color","#000");
	$("#all1").click(function(){
		$("#all1").css("color","#000");
		$("#reg1").css("color","#acacac");
		$("#log1").css("color","#acacac");
		$("#ove1").css("color","#acacac");
		$(".main_use1").show();
		$(".main_use2").hide();
		$(".main_use3").hide();
		$(".main_use4").hide();
	})
	$("#reg1").click(function(){
		$("#reg1").css("color","#000");
		$("#all1").css("color","#acacac");
		$("#log1").css("color","#acacac");
		$("#ove1").css("color","#acacac");
		$(".main_use2").show();
		$(".main_use1").hide();
		$(".main_use3").hide();
		$(".main_use4").hide();
	})
	$("#log1").click(function(){
		$("#log1").css("color","#000");
		$("#reg1").css("color","#acacac");
		$("#all1").css("color","#acacac");
		$("#ove1").css("color","#acacac");
		$(".main_use3").show();
		$(".main_use2").hide();
		$(".main_use1").hide();
		$(".main_use4").hide();
	})
	$("#ove1").click(function(){
		$("#ove1").css("color","#000");
		$("#reg1").css("color","#acacac");
		$("#log1").css("color","#acacac");
		$("#all1").css("color","#acacac");
		$(".main_use4").show();
		$(".main_use2").hide();
		$(".main_use3").hide();
		$(".main_use1").hide();
	})
	$("#all2").click(function(){
		$("#all2").css("color","#000");
		$("#reg2").css("color","#acacac");
		$("#log2").css("color","#acacac");
		$("#ove2").css("color","#acacac");
		$(".main_use1").show();
		$(".main_use2").hide();
		$(".main_use3").hide();
		$(".main_use4").hide();
	})
	$("#reg2").click(function(){
		$("#reg2").css("color","#000");
		$("#all2").css("color","#acacac");
		$("#log2").css("color","#acacac");
		$("#ove2").css("color","#acacac");
		$(".main_use2").show();
		$(".main_use1").hide();
		$(".main_use3").hide();
		$(".main_use4").hide();
	})
	$("#log2").click(function(){
		$("#log2").css("color","#000");
		$("#reg2").css("color","#acacac");
		$("#all2").css("color","#acacac");
		$("#ove2").css("color","#acacac");
		$(".main_use3").show();
		$(".main_use2").hide();
		$(".main_use1").hide();
		$(".main_use4").hide();
	})
	$("#ove2").click(function(){
		$("#ove2").css("color","#000");
		$("#reg2").css("color","#acacac");
		$("#log2").css("color","#acacac");
		$("#all2").css("color","#acacac");
		$(".main_use4").show();
		$(".main_use2").hide();
		$(".main_use3").hide();
		$(".main_use1").hide();
	})
	$("#new").click(function(){
		$(this).addClass("se");
		$("#hot").removeClass("se");
		$(".use_header_ul2").show();
		$(".use_header_ul1").hide();
	})
	$("#hot").click(function(){
		$(this).addClass("se");
		$("#new").removeClass("se");
		$(".use_header_ul1").show();
		$(".use_header_ul2").hide();
	})
})